### ISSUE TITLE
Version issues with related packages

### ISSUE THREAD

**Issue by Christynorl** [WSP-LAB/Link#1]
Hi, I am very interested in your project. I try to implement it on my server, but the latest package does not seem to be applicable to this project. I would like to know the version of these dependent packages. Thank you so much!
![zz](https://github.com/WSP-LAB/Link/assets/34707400/850244f0-4d46-4dce-840d-e063637e8a14)

**Comment by Christynorl** [comment]
Hi, @seongil-wi @soyoungleell ,Can you help me by giving me the version number of the tool related dependencies.I've been stuck with this for a long time.Thank you so much!

**Comment by leexsoyoung** [comment]
Hello, thank you for your question. 

We used anaconda python environment for python package control. 
I exported the experiment environment yaml file. (Link-python.yaml)
You can use it to import conda environment. Or, you can just find the version of the package you want.
Also, we used Python version 3.7.7 for the environment.

I hope this helps.

[Link-python.zip](https://github.com/WSP-LAB/Link/files/11596389/Link-python.zip)
